# Dockerized services for local development.
version: '3'
services:
  postgres:
    container_name: 'wrapped-db'
    image: 'postgres:16.1'
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - POSTGRES_DB=wrapped
      - POSTGRES_USER=${USER}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
